use serde::{Deserialize, Serialize};
use std::cell::RefCell;
use std::collections::HashMap;
use wasm_bindgen::prelude::*;

const SENTE:i8=1; const GOTE:i8=-1; const PROMO:i8=8;
const INF:i32=1_100_000;
const PV:[i32;7]=[0,120,120,95,0,50,130];
const BO:[i32;7]=[0,460,520,300,0,280,600];
const BM:[i32;7]=[0,350,520,300,0,280,600];
const HV:[i32;7]=[0,420,560,320,0,320,690];
const W:[f64;13]=[0.24498569584642743,0.06221710139970306,0.06112076322028654,0.07990383193903985,1.3576909371979942,5.01934717042391,0.38731811453190207,0.08835117987230424,-0.46281649395316404,1.0342490629931143,0.3224410859553111,0.23397259407052765,0.6676808729191774];
const BIAS:f64=-0.33231912708080835;

#[derive(Clone,Deserialize,Serialize)] struct Piece{ id:String, #[serde(rename="type")] kind:String, side:String, promoted:bool }
#[derive(Deserialize)] struct Hands{ sente:Vec<Piece>, gote:Vec<Piece> }
#[derive(Deserialize)] struct State{ board:Vec<Vec<Option<Piece>>>, hands:Hands, turn:String }
#[derive(Clone,Copy)] struct Pos{ b:[i8;36],h:[u8;12],turn:i8,ema:[i8;2] }
#[derive(Clone,Copy,Default)] struct Mv{from:i8,to:u8,kind:u8,cap:i8,promote:bool,piece:u8,magic:u8}
#[derive(Serialize)] struct Action{category:String,piece:Piece,#[serde(skip_serializing_if="Option::is_none")]from:Option<[usize;2]>,to:[usize;2],promote:bool,#[serde(rename="handIndex",skip_serializing_if="Option::is_none")]hand_index:Option<usize>,#[serde(rename="captureAt",skip_serializing_if="Option::is_none")]capture_at:Option<[usize;2]>,#[serde(skip_serializing_if="Option::is_none")]magic:Option<String>,#[serde(rename="movePiece",skip_serializing_if="Option::is_none")]move_piece:Option<bool>,#[serde(skip_serializing_if="Option::is_none")]swap:Option<bool>,#[serde(rename="longForward",skip_serializing_if="Option::is_none")]long_forward:Option<bool>,#[serde(rename="jumpOver",skip_serializing_if="Option::is_none")]jump_over:Option<[usize;2]>}
#[derive(Serialize)] struct SearchResult{action:Action,score:i32,depth:u8,nodes:u64,proven:bool,engine:&'static str}
#[derive(Clone,Copy)] struct Entry{depth:u8,value:i32,flag:u8,best:Mv}
struct Ctx{nodes:u64,deadline:f64,min_depth:u8,tt:HashMap<u64,Entry>,qdepth:u8}
thread_local!{static SHARED_TT:RefCell<HashMap<u64,Entry>>=RefCell::new(HashMap::with_capacity(1<<19));}

fn ti(s:&str)->u8{match s{"nanoka"=>1,"hanna"=>2,"hiro"=>3,"ema"=>4,"sherry"=>5,"margo"=>6,_=>0}}
fn tn(t:u8)->&'static str{match t{1=>"nanoka",2=>"hanna",3=>"hiro",4=>"ema",5=>"sherry",6=>"margo",_=>"nanoka"}}
fn idx(r:i8,c:i8)->u8{(r*6+c)as u8} fn row(i:u8)->i8{(i/6)as i8} fn col(i:u8)->i8{(i%6)as i8}
fn inside(r:i8,c:i8)->bool{r>=0&&r<6&&c>=0&&c<6} fn side(v:i8)->i8{if v>0{1}else{-1}}
fn typ(v:i8)->u8{(v.abs()&7)as u8} fn promoted(v:i8)->bool{v.abs()&PROMO!=0}
fn hi(s:i8,t:u8)->usize{if s==SENTE{(t-1)as usize}else{(6+t-1)as usize}}
fn last(s:i8,r:i8)->bool{if s==SENTE{r==0}else{r==5}}

fn from_state(s:&State)->Pos{let mut p=Pos{b:[0;36],h:[0;12],turn:if s.turn=="sente"{SENTE}else{GOTE},ema:[-1,-1]};for r in 0..6{for c in 0..6{if let Some(q)=&s.board[r][c]{let sd=if q.side=="sente"{SENTE}else{GOTE};let t=ti(&q.kind);let v=sd*((t as i8)+if q.promoted{PROMO}else{0});p.b[r*6+c]=v;if t==4{p.ema[if sd==SENTE{0}else{1}]=(r*6+c)as i8}}}}for q in &s.hands.sente{p.h[hi(SENTE,ti(&q.kind))]+=1}for q in &s.hands.gote{p.h[hi(GOTE,ti(&q.kind))]+=1}p}
fn add(v:&mut Vec<Mv>,from:u8,to:u8,kind:u8,cap:i8,magic:u8){v.push(Mv{from:from as i8,to,kind,cap,promote:false,piece:0,magic})}
fn pseudo(p:&Pos,from:u8,attacks_only:bool)->Vec<Mv>{let v=p.b[from as usize];let s=side(v);let t=typ(v);let pr=promoted(v);let r=row(from);let c=col(from);let f=if s==SENTE{-1}else{1};let mut out=Vec::with_capacity(16);
 let step=|out:&mut Vec<Mv>,dr:i8,dc:i8,can_cap:bool,only_cap:bool|{let rr=r+dr;let cc=c+dc;if !inside(rr,cc){return}let to=idx(rr,cc);let q=p.b[to as usize];if q!=0&&side(q)==s{return}if only_cap&&q==0{return}if q!=0&&!can_cap{return}add(out,from,to,0,if q!=0{to as i8}else{-1},0)};
 let eight=|out:&mut Vec<Mv>|{for dr in -1..=1{for dc in -1..=1{if dr!=0||dc!=0{step(out,dr,dc,true,false)}}}};
 match t{4=>eight(&mut out),1=>{if pr{eight(&mut out)}else{step(&mut out,f,0,true,false);step(&mut out,0,-1,true,false);step(&mut out,0,1,true,false)}for(dc,dr)in[(0,2*f),(-2,2*f),(2,2*f)]{let rr=r+dr;let cc=c+dc;let mr=r+dr/2;let mc=c+dc/2;if inside(rr,cc)&&p.b[idx(mr,mc)as usize]==0{let to=idx(rr,cc);let q=p.b[to as usize];if q!=0&&side(q)!=s{add(&mut out,from,to,1,to as i8,1)}}}},3=>{if pr{eight(&mut out)}else{step(&mut out,f,0,true,false);step(&mut out,0,-1,true,false);step(&mut out,0,1,true,false)}if !attacks_only{for dr in -1..=1{for dc in -1..=1{if dr==0&&dc==0{continue}let rr=r+dr;let cc=c+dc;if inside(rr,cc){let to=idx(rr,cc);let q=p.b[to as usize];if q!=0&&side(q)==s{add(&mut out,from,to,2,-1,2)}}}}}},5=>{if pr{eight(&mut out);let rr=r+2*f;if inside(rr,c)&&p.b[idx(r+f,c)as usize]==0{let to=idx(rr,c);let q=p.b[to as usize];if q==0||side(q)!=s{add(&mut out,from,to,0,if q!=0{to as i8}else{-1},5)}}}else{if !attacks_only{let r1=r+f;let r2=r+2*f;if inside(r1,c)&&p.b[idx(r1,c)as usize]==0{add(&mut out,from,idx(r1,c),0,-1,0)}if inside(r2,c)&&p.b[idx(r1,c)as usize]==0&&p.b[idx(r2,c)as usize]==0{add(&mut out,from,idx(r2,c),0,-1,5)}}step(&mut out,f,-1,true,true);step(&mut out,f,1,true,true)}},6=>{if pr{eight(&mut out)}else{step(&mut out,f,-1,true,false);step(&mut out,f,0,true,false);step(&mut out,f,1,true,false)}let back=-f;for(dr,dc)in[(0,-1),(0,1),(back,-1),(back,0),(back,1)]{let mr=r+dr;let mc=c+dc;let rr=r+2*dr;let cc=c+2*dc;if inside(rr,cc){let mid=idx(mr,mc);let to=idx(rr,cc);let q=p.b[mid as usize];if q!=0&&side(q)!=s&&p.b[to as usize]==0{add(&mut out,from,to,3,mid as i8,3)}}}},2=>{if pr{eight(&mut out)}else{step(&mut out,f,-1,true,false);step(&mut out,f,0,true,false);step(&mut out,f,1,true,false)}if !attacks_only{let rr=r+2*f;if inside(rr,c)&&p.b[idx(rr,c)as usize]==0{add(&mut out,from,idx(rr,c),0,-1,4)}}},_=>{}}out}
// Hot path: answer "can side s capture sq?" without allocating a Vec of pseudo moves.
// check() is called for every candidate move, so the old allocator-heavy version
// dominated the complete search.
fn attacks(p:&Pos,s:i8,sq:u8)->bool{let tr=row(sq);let tc=col(sq);for i in 0..36{let v=p.b[i];if v==0||side(v)!=s{continue}let fr=row(i as u8);let fc=col(i as u8);let dr=tr-fr;let dc=tc-fc;let f=if s==SENTE{-1}else{1};let t=typ(v);if promoted(v){if dr.abs()<=1&&dc.abs()<=1&&(dr!=0||dc!=0){return true}if t==5&&dr==2*f&&dc==0&&p.b[idx(fr+f,fc)as usize]==0{return true}continue}let hit=match t{1=>(dr==f&&dc==0)||(dr==0&&dc.abs()==1)||((dr==2*f&&dc.abs()<=2&&(dc==0||dc.abs()==2))&&p.b[idx(fr+f,fc+dc/2)as usize]==0),2=>dr==f&&dc.abs()<=1,3=>(dr==f&&dc==0)||(dr==0&&dc.abs()==1),4=>dr.abs()<=1&&dc.abs()<=1&&(dr!=0||dc!=0),5=>dr==f&&dc.abs()==1,6=>{if dr==f&&dc.abs()<=1{true}else{let back=-f;(dr==0&&dc.abs()==1||dr==back&&dc.abs()<=1)&&inside(fr+2*dr,fc+2*dc)&&p.b[idx(fr+2*dr,fc+2*dc)as usize]==0}},_=>false};if hit{return true}}false}
fn check(p:&Pos,s:i8)->bool{let e=p.ema[if s==SENTE{0}else{1}];e<0||attacks(p,-s,e as u8)}
fn make(p:&mut Pos,m:Mv){let s=p.turn;if m.kind==4{p.h[hi(s,m.piece)]-=1;p.b[m.to as usize]=s*m.piece as i8}else{let moving=p.b[m.from as usize];let t=typ(moving);if m.kind==2{let q=p.b[m.to as usize];p.b[m.from as usize]=q;p.b[m.to as usize]=if m.promote{s*((t as i8)|PROMO)}else{moving};if typ(q)==4{p.ema[if side(q)==SENTE{0}else{1}]=m.from}}else if m.kind==1{let q=p.b[m.cap as usize];if q!=0&&typ(q)!=4{p.h[hi(s,typ(q))]+=1}p.b[m.cap as usize]=0}else{if m.cap>=0{let q=p.b[m.cap as usize];if q!=0&&typ(q)!=4{p.h[hi(s,typ(q))]+=1}p.b[m.cap as usize]=0}p.b[m.from as usize]=0;p.b[m.to as usize]=if m.promote{s*((t as i8)|PROMO)}else{moving};if t==4{p.ema[if s==SENTE{0}else{1}]=m.to as i8}}}p.turn=-p.turn}
fn generate(p:&Pos)->Vec<Mv>{let mut out=Vec::with_capacity(96);let s=p.turn;for from in 0..36{let v=p.b[from];if v==0||side(v)!=s{continue}for mut m in pseudo(p,from as u8,false){if m.cap>=0&&typ(p.b[m.cap as usize])==4{continue}let t=typ(v);m.promote=m.kind!=1&&t!=4&&!promoted(v)&&(if s==SENTE{row(m.to)<=1}else{row(m.to)>=4});let mut n=*p;make(&mut n,m);if !check(&n,s){out.push(m)}}}for t in 1..=6{if p.h[hi(s,t)]==0{continue}for to in 0..36{if p.b[to]!=0||last(s,row(to as u8)){continue}let m=Mv{from:-1,to:to as u8,kind:4,cap:-1,promote:false,piece:t,magic:0};let mut n=*p;make(&mut n,m);if !check(&n,s){out.push(m)}}}out}
fn terminal(p:&Pos,moves:&[Mv])->Option<(i8,bool)>{for s in[SENTE,GOTE]{let e=p.ema[if s==SENTE{0}else{1}];if e>=0&&last(s,row(e as u8))&&!check(p,s){return Some((s,true))}}if moves.is_empty(){Some((-p.turn,false))}else{None}}
fn try_winner(p:&Pos)->Option<i8>{for s in[SENTE,GOTE]{let e=p.ema[if s==SENTE{0}else{1}];if e>=0&&last(s,row(e as u8))&&!check(p,s){return Some(s)}}None}
fn progress(a:usize,h:i32)->i32{match a{0=>0,1=>if h>=4{-120}else{20},2=>if h>=3{-40}else{90},3=>200,4=>560,_=>1200}}
fn eval(p:&Pos)->i32{let mut count=0;let mut hs=0;let mut hg=0;for i in 0..36{if p.b[i]!=0{count+=1}if row(i as u8)==5&&p.b[i]>0{hs+=1}if row(i as u8)==0&&p.b[i]<0{hg+=1}}let opening=count>=10;let(mut material,mut hand,mut dev,mut promo,mut center,mut prog,mut lock,mut guard,mut finish,mut fixed)=(0,0,0,0,0,0,0,0,0,0);for i in 0..36{let v=p.b[i];if v==0{continue}let s=side(v);let t=typ(v)as usize;let r=row(i as u8);let c=col(i as u8);let a=if s==SENTE{5-r}else{r};let cent=5-((r*2-5).abs()+(c*2-5).abs())/2;if t==4{prog+=s as i32*progress(a as usize,if s==SENTE{hs}else{hg});let rr=r+2*if s==SENTE{-1}else{1};if rr>=0&&rr<6{let q=p.b[idx(rr,c)as usize];if q!=0&&side(q)!=s&&(typ(q)==2||typ(q)==6){lock+=side(q)as i32*if typ(q)==6{220}else{170}}}}else{material+=s as i32*if opening{BO[t]}else{BM[t]};dev+=s as i32*a as i32*14;if opening&&t==2{dev+=s as i32*a as i32*18}if opening&&t==5{dev+=s as i32*a as i32*14}center+=s as i32*cent as i32*6;if promoted(v){promo+=s as i32*190}}fixed+=if t==4{0}else{s as i32*(PV[t]+if promoted(v){25}else{0})}}
 for s in[SENTE,GOTE]{for t in 1..=6{let n=p.h[hi(s,t)]as i32;hand+=s as i32*HV[t as usize]*n;fixed+=s as i32*PV[t as usize]*n}let e=p.ema[if s==SENTE{0}else{1}];if e>=0{for i in 0..36{let v=p.b[i];if v==0{continue}let d=(row(i as u8)-row(e as u8)).abs().max((col(i as u8)-col(e as u8)).abs());if d==1&&side(v)==s&&typ(v)!=4{guard+=s as i32*45}if d<=2&&side(v)!=s&&(typ(v)==2||typ(v)==6){finish+=side(v)as i32*if typ(v)==6{70}else{55}}}}}
 let pressure=|s:i8|->i32{let e=p.ema[if s==SENTE{0}else{1}];if e<0{return 1000}let(mut n,er,ec)=(0,row(e as u8),col(e as u8));for dr in -1..=1{for dc in -1..=1{if dr==0&&dc==0{continue}let rr=er+dr;let cc=ec+dc;if !inside(rr,cc){continue}let v=p.b[idx(rr,cc)as usize];if v!=0&&side(v)!=s{n+=if typ(v)==6{4}else if typ(v)==2||typ(v)==1{3}else{2}}}}n};fixed/=2;let x=[material as f64/500.,hand as f64/500.,dev as f64/300.,promo as f64/300.,center as f64/200.,prog as f64/600.,lock as f64/250.,guard as f64/250.,finish as f64/300.,fixed as f64/300.,pressure(GOTE)as f64/5.,-pressure(SENTE)as f64/5.,1.];let raw=BIAS+W.iter().zip(x).map(|(w,x)|w*x).sum::<f64>();(raw*1000.).round().clamp(-50000.,50000.)as i32}
fn hash(p:&Pos)->u64{let mut h=1469598103934665603u64;for v in p.b{h=(h^(v as i16 as u16 as u64)).wrapping_mul(1099511628211)}for v in p.h{h=(h^v as u64).wrapping_mul(1099511628211)}h^(p.turn as i64 as u64)}
fn tick(c:&mut Ctx)->Result<(),()>{c.nodes+=1;if c.nodes&2047==0&&js_sys::Date::now()>=c.deadline{Err(())}else{Ok(())}}
fn order_score(p:&Pos,m:Mv,preferred:Option<Mv>)->i32{if preferred.map(|x|same_move(x,m)).unwrap_or(false){return 2_000_000}let mut n=0;if m.cap>=0{let victim=typ(p.b[m.cap as usize])as usize;n+=100_000+PV[victim]*16-PV[typ(p.b[m.from.max(0)as usize])as usize]}if m.promote{n+=20_000}let s=p.turn;if typ(if m.from>=0{p.b[m.from as usize]}else{s*m.piece as i8})==4&&last(s,row(m.to)){n+=1_000_000}n}
fn qsearch(p:&mut Pos,q:u8,mut a:i32,mut b:i32,c:&mut Ctx)->Result<i32,()>{tick(c)?;if let Some(w)=try_winner(p){return Ok((if w==SENTE{1}else{-1})*1_000_000)}let stand=eval(p);if q==0{return Ok(stand)}let max=p.turn==SENTE;if max{if stand>=b{return Ok(stand)}a=a.max(stand)}else{if stand<=a{return Ok(stand)}b=b.min(stand)}let s=p.turn;let mut noisy:Vec<Mv>=generate(p).into_iter().filter(|m|m.cap>=0||m.promote||(m.from>=0&&typ(p.b[m.from as usize])==4&&last(s,row(m.to)))).collect();noisy.sort_unstable_by_key(|m|-order_score(p,*m,None));let mut best=stand;for m in noisy{let old=*p;make(p,m);let result=qsearch(p,q-1,a,b,c);*p=old;let v=result?;if(max&&v>best)||(!max&&v<best){best=v}if max{a=a.max(best)}else{b=b.min(best)}if a>=b{break}}Ok(best)}
fn search(p:&mut Pos,d:u8,mut a:i32,mut b:i32,c:&mut Ctx)->Result<i32,()>{tick(c)?;if let Some(w)=try_winner(p){return Ok((if w==SENTE{1}else{-1})*1_000_000+if w==SENTE{d as i32}else{-(d as i32)})}if d==0{return qsearch(p,c.qdepth,a,b,c)}let key=hash(p);let cached=c.tt.get(&key).copied();if let Some(e)=cached{if e.depth>=d{if e.flag==0{return Ok(e.value)}if e.flag==1{a=a.max(e.value)}else{b=b.min(e.value)}if a>=b{return Ok(e.value)}}}let mut moves=generate(p);if moves.is_empty(){return Ok((if p.turn==SENTE{-1}else{1})*900_000)}let max=p.turn==SENTE;let a0=a;let b0=b;let preferred=cached.map(|e|e.best);moves.sort_unstable_by_key(|m|-order_score(p,*m,preferred));let mut best=if max{-INF}else{INF};let mut bm=Mv::default();let mut first=true;for m in moves{let old=*p;make(p,m);let result=if first{search(p,d-1,a,b,c)}else if max{let z=search(p,d-1,a,a.saturating_add(1),c);match z{Ok(mut v)=>{if v>a&&v<b{v=search(p,d-1,a,b,c)?}Ok(v)},Err(e)=>Err(e)}}else{let z=search(p,d-1,b.saturating_sub(1),b,c);match z{Ok(mut v)=>{if v<b&&v>a{v=search(p,d-1,a,b,c)?}Ok(v)},Err(e)=>Err(e)}};*p=old;let v=result?;first=false;if(max&&v>best)||(!max&&v<best){best=v;bm=m}if max{a=a.max(best)}else{b=b.min(best)}if a>=b{break}}let flag=if best<=a0{2}else if best>=b0{1}else{0};c.tt.insert(key,Entry{depth:d,value:best,flag,best:bm});Ok(best)}
fn same_move(a:Mv,b:Mv)->bool{a.from==b.from&&a.to==b.to&&a.kind==b.kind&&a.cap==b.cap&&a.promote==b.promote&&a.piece==b.piece}
fn root(p:&mut Pos,d:u8,mut a:i32,mut b:i32,c:&mut Ctx)->Result<(Mv,i32),()>{let max=p.turn==SENTE;let preferred=c.tt.get(&hash(p)).map(|e|e.best);let mut moves=generate(p);moves.sort_unstable_by_key(|m|-order_score(p,*m,preferred));let mut best=if max{-INF}else{INF};let mut bm=*moves.first().ok_or(())?;let mut first=true;for m in moves{let old=*p;make(p,m);let result=if first{search(p,d-1,a,b,c)}else if max{let z=search(p,d-1,a,a.saturating_add(1),c);match z{Ok(mut v)=>{if v>a&&v<b{v=search(p,d-1,a,b,c)?}Ok(v)},Err(e)=>Err(e)}}else{let z=search(p,d-1,b.saturating_sub(1),b,c);match z{Ok(mut v)=>{if v<b&&v>a{v=search(p,d-1,a,b,c)?}Ok(v)},Err(e)=>Err(e)}};*p=old;let v=result?;first=false;if(max&&v>best)||(!max&&v<best){best=v;bm=m}if max{a=a.max(best)}else{b=b.min(best)}}Ok((bm,best))}
fn action(s:&State,m:Mv)->Action{let (piece,hand_index)=if m.kind==4{let hs=if s.turn=="sente"{&s.hands.sente}else{&s.hands.gote};let i=hs.iter().position(|q|ti(&q.kind)==m.piece).unwrap_or(0);(hs[i].clone(),Some(i))}else{(s.board[row(m.from as u8)as usize][col(m.from as u8)as usize].as_ref().unwrap().clone(),None)};let magic=match m.magic{1=>Some("銃撃".into()),2=>Some("居合切り".into()),3=>Some("跳躍暗殺".into()),4=>Some("浮遊".into()),_=>None};Action{category:if magic.is_some(){"magic".into()}else if m.kind==4{"drop".into()}else{"move".into()},piece,from:if m.from<0{None}else{Some([row(m.from as u8)as usize,col(m.from as u8)as usize])},to:[row(m.to)as usize,col(m.to)as usize],promote:m.promote,hand_index,capture_at:if m.cap>=0{Some([row(m.cap as u8)as usize,col(m.cap as u8)as usize])}else{None},magic,move_piece:if m.kind==1{Some(false)}else if m.kind==3||m.magic==4{Some(true)}else{None},swap:if m.kind==2{Some(true)}else{None},long_forward:if m.magic==5{Some(true)}else{None},jump_over:if m.magic==4{Some([((row(m.from as u8)+row(m.to))/2)as usize,col(m.from as u8)as usize])}else{None}}}

#[wasm_bindgen]
pub fn engine_version()->String{"magical-shogi-rust-wasm-0.2.1-fullwidth".into()}

#[wasm_bindgen]
pub fn reset_engine(){SHARED_TT.with(|tt|tt.borrow_mut().clear())}

#[wasm_bindgen]
pub fn best_action(state:JsValue,max_depth:u8,min_depth:u8,time_limit_ms:f64)->Result<JsValue,JsValue>{let s:State=serde_wasm_bindgen::from_value(state).map_err(|e|JsValue::from_str(&e.to_string()))?;let mut p=from_state(&s);let started=js_sys::Date::now();let hard_deadline=started+time_limit_ms;let tt=SHARED_TT.with(|shared|std::mem::take(&mut*shared.borrow_mut()));let mut c=Ctx{nodes:0,deadline:hard_deadline,min_depth,tt,qdepth:4};let(mut best,mut score,mut done)=(None,0,0);let mut d=1;while d<=max_depth{c.deadline=hard_deadline;let window=if done==0{(-INF,INF)}else{(score-180,score+180)};let attempt=root(&mut p,d,window.0,window.1,&mut c).and_then(|x|if x.1<=window.0||x.1>=window.1{root(&mut p,d,-INF,INF,&mut c)}else{Ok(x)});match attempt{Ok((m,v))=>{best=Some(m);score=v;done=d},Err(_)=>break}d+=2}if c.tt.len()>1_000_000{c.tt.clear()}let nodes=c.nodes;let saved_tt=c.tt;SHARED_TT.with(|shared|*shared.borrow_mut()=saved_tt);let m=best.ok_or_else(||JsValue::from_str("no legal action"))?;serde_wasm_bindgen::to_value(&SearchResult{action:action(&s,m),score,depth:done,nodes,proven:false,engine:"wasm"}).map_err(|e|JsValue::from_str(&e.to_string()))}
