import {useEffect,useMemo,useRef,useState} from "react";
import "./App.css";
import {FILES,RANKS,PIECES,makeInitialState,generateAllLegalActions,applyLegalAction,terminalResult,actionLabel,isEmmaInCheck,squareName} from "./game/rules.js";
import {stateKey,valueScore,winRate} from "./game/aiEngine.js";
const imageFor=p=>`/images/pieces/${p.type}_${p.promoted?"red":"black"}.png`;
function Piece({piece,compact=false,perspective="sente"}){return <div className={`piece ${piece.side!==perspective?"piece--opponent":""} ${compact?"piece--compact":""}`}><span className="piece-fallback">{PIECES[piece.type].short}</span><img src={imageFor(piece)} alt={PIECES[piece.type].name} draggable={false} onError={e=>{e.currentTarget.style.display="none"}}/></div>}
function Hand({title,pieces,active,onPick,disabled,perspective}){return <div className="hand"><div className="hand-title">{title}</div><div className="hand-pieces">{pieces.length?pieces.map((p,i)=><button disabled={disabled} key={`${p.type}-${i}`} className={`hand-piece ${active===i?"active":""}`} onClick={()=>onPick(i)}><Piece piece={p} compact perspective={perspective}/><span>{PIECES[p.type].short}</span></button>):<span className="hand-empty">なし</span>}</div></div>}
export default function App(){
 const initial=useMemo(()=>makeInitialState(),[]),[timeline,setTimeline]=useState([initial]),[humanSide,setHumanSide]=useState("sente"),[selected,setSelected]=useState(null),[handIndex,setHandIndex]=useState(null),[thinking,setThinking]=useState(false),[engine,setEngine]=useState(null),[error,setError]=useState("");
 const worker=useRef(null),request=useRef(0),state=timeline[timeline.length-1],result=useMemo(()=>terminalResult(state),[state]),seen=useMemo(()=>timeline.map(stateKey),[timeline]);
 const legal=useMemo(()=>result?[]:generateAllLegalActions(state),[state,result]);
 const selectable=useMemo(()=>legal.filter(a=>a.category==="drop"?handIndex!==null&&a.handIndex===handIndex:selected&&a.from?.[0]===selected[0]&&a.from?.[1]===selected[1]),[legal,selected,handIndex]);
 useEffect(()=>{worker.current=new Worker(new URL("./game/ai.worker.js",import.meta.url),{type:"module"});return()=>worker.current?.terminate()},[]);
 useEffect(()=>{if(result||!worker.current)return;if(state.turn===humanSide){worker.current.postMessage({type:"ponder",state,seen});return}setThinking(true);setError("");const id=++request.current;worker.current.onmessage=({data})=>{if(data.id!==id)return;setThinking(false);if(data.error){setError(data.error);return}if(!data.result)return;setEngine({label:actionLabel(state,data.result.action),score:data.result.score,depth:data.result.depth,nodes:data.result.nodes});setTimeline(x=>[...x,applyLegalAction(x[x.length-1],data.result.action)])};worker.current.postMessage({type:"think",id,state,seen})},[state,humanSide,result,seen]);
 function play(a){if(thinking||state.turn!==humanSide||result)return;setEngine(null);setTimeline(x=>[...x,applyLegalAction(x[x.length-1],a)]);setSelected(null);setHandIndex(null)}
 function click(r,c){if(thinking||state.turn!==humanSide||result)return;const choices=selectable.filter(a=>a.to[0]===r&&a.to[1]===c);if(choices.length){play(choices.find(a=>a.magic)||choices[0]);return}const p=state.board[r][c];if(p?.side===humanSide){setSelected([r,c]);setHandIndex(null)}else setSelected(null)}
 function reset(side=humanSide){request.current++;worker.current?.postMessage({type:"reset"});setTimeline([makeInitialState()]);setHumanSide(side);setSelected(null);setHandIndex(null);setEngine(null);setError("");setThinking(false)}
 const targets=new Map(selectable.map(a=>[`${a.to[0]},${a.to[1]}`,a]));
 const viewRows=humanSide==="gote"?[5,4,3,2,1,0]:[0,1,2,3,4,5],viewCols=humanSide==="gote"?[5,4,3,2,1,0]:[0,1,2,3,4,5];
 const viewFiles=humanSide==="gote"?[...FILES].reverse():FILES,viewRanks=humanSide==="gote"?[...RANKS].reverse():RANKS;
 const opponentSide=humanSide==="sente"?"gote":"sente",sideName=side=>side==="sente"?"先手":"後手";
 return <div className="app-shell"><header className="topbar"><div><div className="eyebrow">MANOSABA SHOGI AI</div><h1>魔法少女ノ魔法将棋</h1></div><div className={`turn-badge turn-badge--${state.turn}`}>{result?`${result.winner==="sente"?"先手":"後手"}勝ち`:thinking?"AI思考中":state.turn==="sente"?"先手番":"後手番"}{!result&&isEmmaInCheck(state,state.turn)&&<span className="check-label">王手</span>}</div></header>
 <div className="side-picker"><button className={humanSide==="sente"?"active":""} onClick={()=>reset("sente")}>先手で対戦</button><button className={humanSide==="gote"?"active":""} onClick={()=>reset("gote")}>後手で対戦</button><button onClick={()=>reset()}>最初から</button></div>
 <main className="ai-layout"><section><Hand title={`${sideName(opponentSide)} 持ち駒`} pieces={state.hands[opponentSide]} disabled active={null} onPick={()=>{}} perspective={humanSide}/><div className="board-frame"><div className="coords coords--top">{viewFiles.map(x=><span key={x}>{x}</span>)}</div><div className="board-wrap"><div className="board-container"><div className="board">{viewRows.map(r=>viewCols.map(c=>{const p=state.board[r][c],key=`${r},${c}`,target=targets.get(key);return <button key={key} onClick={()=>click(r,c)} className={`square ${(r+c)%2?"square--alt":""} ${selected?.[0]===r&&selected?.[1]===c?"square--selected":""} ${target?(target.category==="magic"?"square--magic-target":"square--move-target"):""}`}>{p&&<Piece piece={p} perspective={humanSide}/>}<span className="square-label">{squareName(r,c)}</span></button>}))}</div></div><div className="coords coords--right">{viewRanks.map(x=><span key={x}>{x}</span>)}</div></div></div><Hand title={`${sideName(humanSide)} 持ち駒`} pieces={state.hands[humanSide]} disabled={state.turn!==humanSide||thinking} active={handIndex} onPick={i=>{setHandIndex(i);setSelected(null)}} perspective={humanSide}/></section>
 <aside className="ai-status panel-card"><div className="panel-title">思考AI</div><div className="engine-meta"><span>評価器</span><strong>V66 数値探索</strong><span>教師局面</span><strong>1,352,844</strong><span>現在評価</span><strong>{valueScore(state)>0?"+":""}{valueScore(state)}</strong><span>先手勝率</span><strong>{winRate(state).toFixed(1)}%</strong></div>{engine&&<div className="suggestion">直前のAI着手<br/><b>{engine.label}</b><br/>到達深度：{engine.depth}手<br/>探索値：{engine.score>0?"+":""}{engine.score}</div>}{error&&<div className="suggestion">AIエラー：{error}</div>}<div className="history">{timeline.slice(1).map((s,i)=><div className="history-row" key={i}><span>{i+1}</span><span>{s.note||"着手済み"}</span></div>)}</div></aside></main></div>
}
